name: Deploy VayGo API

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Main
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master

        with:
          host: 187.127.162.37
          username: root
          password: ${{ secrets.VPS_PASSWORD }}

          script: |
            cd /root/VayGoAPI/WebApplication1/WebApplication1
            git pull origin main
            docker build -t vaygo-api .
            docker rm -f vaygo-container || true
            docker run -d -p 80:8080 --name vaygo-container vaygo-api

      - name: Deploy Development
        if: github.ref == 'refs/heads/development'
        uses: appleboy/ssh-action@master

        with:
          host: 187.127.162.37
          username: root
          password: ${{ secrets.VPS_PASSWORD }}

          script: |
            cd /root/VayGoAPI/WebApplication1/WebApplication1
            git pull origin development
            docker build -t vaygo-api-dev .
            docker rm -f vaygo-dev-container || true
            docker run -d -p 8081:8080 --name vaygo-dev-container vaygo-api-dev
